# fly.toml app configuration file generated for afbo on 2024-10-22T11:01:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'afbo'
primary_region = 'arn'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
